// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Both platforms live in the Locafy project (locafy-7461b) as app.locafy.customer.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-OjpFwhfNLN_BuK-ST82PNfUE7WvTUnI',
    appId: '1:569055083015:android:5b5bb77153622c178fc8a2',
    messagingSenderId: '569055083015',
    projectId: 'locafy-7461b',
    storageBucket: 'locafy-7461b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjj4Um_55g9qa2FzZ-SJdkm878erCToBc',
    appId: '1:569055083015:ios:d5213f4b36c38c3d8fc8a2',
    messagingSenderId: '569055083015',
    projectId: 'locafy-7461b',
    storageBucket: 'locafy-7461b.firebasestorage.app',
    iosBundleId: 'app.locafy.customer',
  );
}
